### ISSUE TITLE
URL Cleanup Stomps Hash Values

### ISSUE THREAD

**Issue by benlongo** [swan-io/chicane#42]
### Bug summary

Many authentication libraries work by providing information in a redirect URI and extracting it once the app loads. However, the URL cleanup logic here https://github.com/swan-io/chicane/blob/main/src/history.ts#L30 can change the `window.location` which breaks other libraries. 

For example https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5091 happens because this rewrites the hash value to be url encoded and removes the `=` character

I think that the URL cleanup logic has to be modified to not URL encode the hash but I'm unsure how to do that. 

### Library version

1.3.4

### Environment info

```shell
https://whatismybrowser.com/w/B3AX26B
```

### Steps to reproduce

1. Load a page that uses chicane
2. Add a hash like `#foo=bar`
3. Refresh the page
4. Observe the URL encoded value

**Comment by zoontek** [comment]
@benlongo we just released [a patch version](https://github.com/swan-io/chicane/releases/tag/1.4.1) that remove this behaviour. It's indeed a bit too dangerous to perform in unknown environments.
It's not breaking at all, since even if they are not cleaned, route will still match correctly. Give it a try 🙂

**Comment by benlongo** [comment]
Thanks! That resolve the issue.
